// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLyjd0Sj2pcE52HEmrdNIVUf1npojwrcs',
    appId: '1:741669962898:web:9a5d58a0cca453af67924b',
    messagingSenderId: '741669962898',
    projectId: 'sporent-80b28',
    authDomain: 'sporent-80b28.firebaseapp.com',
    storageBucket: 'sporent-80b28.appspot.com',
    measurementId: 'G-F49RRD03SE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2x1V7uqc0TEoejpFFr3dNj-KPvc4L7-k',
    appId: '1:741669962898:android:a2e49a38b60e84d867924b',
    messagingSenderId: '741669962898',
    projectId: 'sporent-80b28',
    storageBucket: 'sporent-80b28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH4aD0XxiNV_Kr0TbwSv4qBIsA1syU8uY',
    appId: '1:741669962898:ios:46401daf9e8f5eec67924b',
    messagingSenderId: '741669962898',
    projectId: 'sporent-80b28',
    storageBucket: 'sporent-80b28.appspot.com',
    androidClientId: '741669962898-0t825qs551snn7k89tl3f7afk76bf336.apps.googleusercontent.com',
    iosClientId: '741669962898-m79o1g1pijjq61suldfg5k4f6a6a88h7.apps.googleusercontent.com',
    iosBundleId: 'com.sporent.sporent',
  );
}
